### ISSUE TITLE
Dashboard stats incorrect

### ISSUE THREAD

**Issue by joshnucks** [ifit/active-dashboard#1]
#### Bug Details

- - -

**Bug Description**
Stats are coming up as values higher than they should, on the site. In this case the cal consumed is 60 and should be 40, net cal is 1368 and should be 762. The correct values are being displayed on the band and the app.
**How many users are experiencing it?**
 at least 2
**What are the user names of those users? (at least 2 please)**
jnucks and joshnuckles
**Reason for fixing?**
Wrong stats are of little use
**Screen Shot**
![image](https://cloud.githubusercontent.com/assets/11634273/7374188/f9d88b2c-ed8d-11e4-8e7c-c1a9f8bcd85e.png)
https://drive.google.com/a/ifit.com/file/d/0B3q9nsoajuzscC13TjJzR3Q1dVE5eFA0Ulk1VUZYWGVhaERJ/view?usp=sharing
**Reproduction Steps**
1. enter nutrition items on the site (I did 2 of the same item, almost an hour apart for 40 cal)
2. Refresh and sync everything
3. Compare values
**Browser/Platform/Machine Details**
Chrome, iPhone 5S, Galaxy S6, active band
@joeyhdez10

**Comment by jondavidjohn** [comment]
I believe you've got the wrong repository.

**Comment by joeyhdez10** [comment]
@jondavidjohn I had him put it on the web because he logged the food items on the website and the website dashboard was displaying it incorrectly. But it seems as if the app received the data correctly. Therefore to me it sounds like the api that sends data to the phone is working but the api that send logged food calories to the dashboard is broke. Either way we will investigate further and I will notify you when it has enough data.

**Comment by jondavidjohn** [comment]
@joeyhdez10 this is the wrong repository though... ifit/active-dashboard, not ifit/ifit.

**Comment by joeyhdez10** [comment]
@jondavidjohn Haha I thought this was in ifit/ifit. I'll get it moved. Thanks

**Comment by jondavidjohn** [comment]
:+1:
